### ISSUE TITLE
198v2 Breaks Everything

### ISSUE THREAD

**Issue by 2322git** [ZephyrXD/Free-Z-Builder-Source#1]
I have tried to compile the project with an edited stub (added savedecrypter adaptability and disable antivirus, for learning the language) but for some reason I have to keep deleting C:\Temp due to exceptions with ConfuserEx.zip and CommonServiceLocator.dll, I upgraded to VMProtect afterwards but you really should fix that.

**Comment by Bexpg-0** [comment]
> I have tried to compile the project with an edited stub (added savedecrypter adaptability and disable antivirus, for learning the language) but for some reason I have to keep deleting C:\Temp due to exceptions with ConfuserEx.zip and CommonServiceLocator.dll, I upgraded to VMProtect afterwards but you really should fix that.

Send source i fix for u

**Comment by ZeppyXD** [comment]
Yeah, that is why I removed obfuscation. Sorry about that
