### ISSUE TITLE
Error while building (form1 opening form2)

### ISSUE THREAD

**Issue by Benjjiyy** [ZephyrXD/Free-Z-Builder-Source#3]
Line	Suppression State Error	CS7036	There is no argument given that corresponds to the required formal parameter 'ID' of 'Form2.Form2(string)

**Comment by ZeppyXD** [comment]
Remove the parameters in the Form2 method and whenever the ID parameter is used in the method.

**Comment by Benjjiyy** [comment]
alr, what do i do about the antidelete

**Comment by ZeppyXD** [comment]
Compile AntiDelete.cs and add that executable

**Comment by Benjjiyy** [comment]
aight thx bbygirl

**Comment by Benjjiyy** [comment]
wait no wtf i still gert the error
Error	CS0117	'Resources' does not contain a definition for 'AntiDelete'

**Comment by Benjjiyy** [comment]
Wait i fixed it

**Comment by Benjjiyy** [comment]
aight thx bbygirl

**Comment by Benjjiyy** [comment]
nope while building the stealer i get this:
![image](https://user-images.githubusercontent.com/66467596/101686105-e2bd5200-3a68-11eb-87d4-a2b6adb87ae6.png)

**Comment by StexHub** [comment]
dm Stexie#4113

**Comment by StexHub** [comment]
don't add antidelete. remove all calls in source and remove from resources.
